Make indentation consistent in scripts

diff --git a/tools/scripts/lux-build.in b/tools/scripts/lux-build.in
--- a/tools/scripts/lux-build.in
+++ b/tools/scripts/lux-build.in
@@ -200,12 +200,12 @@ while test "$#" -gt 0; do
 	a="$1"
 	shift
 	case "$a" in
-		"-f" | "--feature")	kind=feature;;
-		"-h" | "--help")	kind=src; help;;
-		"-o")	kind=src; mod="$1";      shift;;
-		"-i")	kind=src; dir="$1";      shift;;
-		"+i")	kind=src; dir="$dir/$1"; shift;;
-		*)	test "$kind" == "src" && ina+=("$a") || feature "$a";;
+	"-f" | "--feature")	kind=feature;;
+	"-h" | "--help")	kind=src; help;;
+	"-o")	kind=src; mod="$1";      shift;;
+	"-i")	kind=src; dir="$1";      shift;;
+	"+i")	kind=src; dir="$dir/$1"; shift;;
+	*)	test "$kind" == "src" && ina+=("$a") || feature "$a";;
 	esac
 done
 
@@ -214,19 +214,19 @@ done
 for i in "${ina[@]}"; do
 	if test -f "$i"; then
 		case "$i" in
-			*.c)	src+=("$i");;
-			*.h)	echo "\"$i\" is a header file; SKIP";;
-			*)	echo "Invalid input file \"$i\"; ABORT"
-				exit 1
-				;;
+		*.c)	src+=("$i");;
+		*.h)	echo "\"$i\" is a header file; SKIP";;
+		*)	echo "Invalid input file \"$i\"; ABORT"
+			exit 1
+			;;
 		esac
 	else
 		case "$i" in
-			-I*)	cpp+=("$i");;
-			-[Ll]*)	ld+=("$i");;
-			*)	echo "Input flag \"$i\"; ABORT"
-				exit 1
-				;;
+		-I*)	cpp+=("$i");;
+		-[Ll]*)	ld+=("$i");;
+		*)	echo "Input flag \"$i\"; ABORT"
+			exit 1
+			;;
 		esac
 	fi
 done
diff --git a/tools/scripts/lux-install.in b/tools/scripts/lux-install.in
--- a/tools/scripts/lux-install.in
+++ b/tools/scripts/lux-install.in
@@ -51,10 +51,10 @@ while test "$#" -gt 0; do
 	a="$1"
 	shift
 	case "$a" in
-		"-h" | "--help")	help;;
-		"-i")	dir="$1";      shift;;
-		"+i")	dir="$dir/$1"; shift;;
-		*)	ina+=("$a");;
+	"-h" | "--help")	help;;
+	"-i")	dir="$1";      shift;;
+	"+i")	dir="$dir/$1"; shift;;
+	*)	ina+=("$a");;
 	esac
 done
 
@@ -63,11 +63,11 @@ done
 for i in "${ina[@]}"; do
 	if test -f "$i"; then
 		case "$i" in
-			*.la)	mod+=("$i");;
-			*.cl)	mod+=("$i");;
-			*)	echo "Invalid module \"$i\"; ABORT"
-				exit 1
-				;;
+		*.la)	mod+=("$i");;
+		*.cl)	mod+=("$i");;
+		*)	echo "Invalid module \"$i\"; ABORT"
+			exit 1
+			;;
 		esac
 	else
 		echo "Input module \"$i\" not found; ABORT"
