Check status code after compilation and linking; abort if necessary

diff --git a/src/lux-mksim.in b/src/lux-mksim.in
--- a/src/lux-mksim.in
+++ b/src/lux-mksim.in
@@ -104,6 +104,17 @@ INSTALL="@INSTALL@"
 mod_CPPFLAGS="-DLUX_MOD_NAME=${out%.la}"
 mod_LIBADD="${libdir}/libux.la"
 
+# Clean up---we do not track timestamp of the dependencies so there is
+# no reason to keep the intermediate files
+function cleanup {
+	echo "Cleaning up intermediate files"
+	rm -rf .libs _libs
+	rm -f "$out"
+	rm -f *.$OBJEXT
+	rm -f *.lo
+}
+trap cleanup EXIT
+
 # Compile the source file(s) to object(s)
 for s in "${src[@]}"; do
 	o="${s%c}lo"
@@ -113,6 +124,11 @@ for s in "${src[@]}"; do
 		${AM_CPPFLAGS} ${CPPFLAGS}          \
 		${AM_CFLAGS} ${CFLAGS}              \
 		"$s" ${mod_CPPFLAGS} -o "$o"
+	status=$?
+	if test $status -ne 0; then
+		echo "FAILED COMPILING \"$s\" TO \"$o\"; ABORT"
+		exit $status
+	fi
 	obj+=("$o")
 done
 
@@ -132,15 +148,13 @@ ${LIBTOOL} --tag=CC --mode=link ${CCLD} \
 	${AM_LDFLAGS} ${LDFLAGS}        \
 	${LIBS} ${DEFAULT_RPATH}        \
 	"${obj[@]}" ${mod_LIBADD} -o "$out"
+status=$?
+if test $status -ne 0; then
+	echo "FAILED LINKING OBJECT FILE(S) TO \"$out\"; ABORT"
+	exit $status
+fi
 
 # Install output module to "$dir"
 echo "Install \"$out\" to \"$dir\""
 mkdir -p "$PWD/$dir"
 ${LIBTOOL} --mode=install ${INSTALL} "$out" "$PWD/$dir"
-
-# Clean up---we do not track timestamp of the dependencies so there is
-# no reason to keep the intermediate files
-rm -rf .libs _libs
-rm -f "$out"
-rm -f *.$OBJEXT
-rm -f *.lo
